spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: systemsage_user
    password: Panchajanyam@123

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
    secret: AtFjLwqphRYcIzIcbcPyh6PXmB/eOlS2ELcsrGDlyiw=
    expiration: 86400000
